Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          'Flownative.Neos.LastPublisher:PublishingHistoryEditor':
            resource: resource://Flownative.Neos.LastPublisher/Public/PublishingHistoryEditor/Plugin.css
        javascript:
          'Flownative.Neos.LastPublisher:PublishingHistoryEditor':
            resource: resource://Flownative.Neos.LastPublisher/Public/PublishingHistoryEditor/Plugin.js
      frontendConfiguration:
        'Flownative.Neos.LastPublisher:PublishingHistoryEditor':
            # The maximum number of items to show in the publishing history editor
            maximumItems: '${Configuration.setting("Flownative.Neos.LastPublisher.PublishingHistoryEditor.maximumItems")}'

    userInterface:
      translation:
        autoInclude:
          Flownative.Neos.LastPublisher:
            - 'NodeTypes/Mixin/*'
            - Main
